import type { Metadata } from "next";
import "./globals.css";
import { GoogleAnalytics } from "./components/googleAnalytic";
import { getSubDomainServerSide } from "@/utils/subdomainServerSide";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const domain = getSubDomainServerSide()
  console.log('layout domain:' , domain)
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <GoogleAnalytics />
      </body>
    </html>
  );
}
